name: KMMBridge Publish Release
on:
  workflow_dispatch:
    secrets:
      ACTIONS_USERNAME:
        required: true
      ACTIONS_TOKEN:
        required: true

jobs:
  set-netrc:
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/netrc@v1
        with:
          machine: maven.pkg.github.com
          username: ${{ secrets.ACTIONS_USERNAME }}
          password: ${{ secrets.ACTIONS_TOKEN }}

  call-kmmbridge-publish:
    permissions:
      contents: write
      packages: write
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.9
