name: KMMBridge Publish Release
on:
  workflow_dispatch:
    secrets:
      ACTIONS_USERNAME: ${{ secrets.ACTIONS_USERNAME }}
      ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}


jobs:
  call-kmmbridge-publish:
    permissions:
      contents: write
      packages: write
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.9