name: KMMBridge Publish Release
on:
  workflow_dispatch:
    secrets:
      actions_username:
        type: string
        required: true
      actions_token :
        type: string
        required: true

jobs:
  call-kmmbridge-publish:
    permissions:
      contents: write
      packages: write
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.9
    secrets:
      ACTIONS_USERNAME: ${{ inputs.ACTIONS_USERNAME }}
      ACTIONS_TOKEN: ${{ inputs.ACTIONS_TOKEN }}