name: KMMBridge Publish Release
on: workflow_dispatch

jobs:
  call-kmmbridge-publish:
    secrets:
      ACTIONS_USERNAME: ${{ secrets.ACTIONS_USERNAME }}
      ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
    permissions:
      contents: write
      packages: write
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.9