name: KMMBridge Publish Release
on: workflow_dispatch

jobs:
  call-kmmbridge-publish:
    permissions:
      contents: write
      packages: write
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.9
    with:
      machine: maven.pkg.github.com/
      username: ${{ secrets.ACTIONS_USERNAME }}
      password: ${{ secrets.ACTIONS_TOKEN }}